### ISSUE TITLE
Date string parsing simplify and test timezones

### ISSUE THREAD

**Issue by holdenrehg** [Yenthe666/rental#10]
I referenced this in https://github.com/Yenthe666/rental/pull/9 .

---

I have seen a specific issue, but the way I wrote the date/time handling pieces are worrisome. Sometimes strings are passed around, sometimes `datetime` objects.

I want to make sure that there's a single point of entry for handling time with this. I created a helper function `parse_datetime` for this, so that everything can funnel through there.

Two goals here:
1. Simplify the code, try to work consistently with `datetime` objects and anytime strings are necessary, convert them to `datetime` objects as soon as possible always using a consist function (`parse_datetime`).
2. Test timezones. Make sure we are handling timezones correctly, and get unit tests written for it.

**Comment by Yenthe666** [comment]
@holdenrehg if I'm not mistaking we should have this covered in https://github.com/Yenthe666/rental/commit/609fc4c861ec51ce49f24a946209f21ea7dc7d67 now?

**Comment by holdenrehg** [comment]
Not 100%. It's stable as of now but I think there's some places that could be improved, but if you're happy for now @Yenthe666  I'll save refactoring for later.
