### ISSUE TITLE
Clicking twice on "Check Availability" breaks JS

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/rental#12]
Steps to reproduce:
1. Install the app and go to a rental product in the webshop
2. Click on the button "Check Availability"
3. Close the availability dialog and open it up again
4. Error!

```
Traceback:
Error: Template website_rentals.RentalWizard already defined
```

@holdenrehg we have to do a check if the dialog is already defined/loaded before or not.

**Comment by holdenrehg** [comment]
@Yenthe666 are we good to close this one down?

**Comment by Yenthe666** [comment]
Yes, sorry :) Fixed in https://github.com/Yenthe666/rental/commit/10233751044446ae9dd1e25e0b1b2ab0b1c0f675
