### ISSUE TITLE
Can't find a required module

### ISSUE THREAD

**Issue by waltherB** [Yenthe666/rental#22]
Hi Yenthe

Where on earth do I find the required module: sale_stock_renting

**Comment by nickchacha** [comment]
> Hi Yenthe
> 
> Where on earth do I find the required module: sale_stock_renting

@waltherB did you ever got a way around the missing called modules? 
@Yenthe666  will be greatly awesome if you can assist with this 2 (sale_stock_renting, sale_renting)

**Comment by waltherB** [comment]
Nope. Went with a self hosted calcom docker instance and some manual processes.

**Comment by nickchacha** [comment]
Do you think they forgot to include or it was deliberately left out ? :smiley:

**Comment by waltherB** [comment]
No clue 😁. Just gave up in the end, and I think I'll leave it with that as I'm moving on to v17 and have to dig into what I'll be able to conjure up there ( hint: calcom and manual processes)

**Comment by Yenthe666** [comment]
Both apps are in the source code of Odoo enterprise. See https://github.com/odoo/enterprise/tree/15.0/sale_stock_renting and https://github.com/odoo/enterprise/tree/15.0/sale_renting
Without enterprise code/access you cannot use our app. I hope this helps :)

P.S: Sorry I missed the previous messages, I get about 200-400 a day..

**Comment by nickchacha** [comment]
Fair enough bro
Thanks for taking time to reply.

**Comment by waltherB** [comment]
Makes sence now. Thanks

**Comment by Yenthe666** [comment]
Happy to hear, you're welcome :)
