### ISSUE TITLE
Unable to translate dialog

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/rental#3]
Steps:
1. Open up a rental product in the website in another language than English (de_CH as a sample):
![image](https://user-images.githubusercontent.com/6352350/128672057-f1d1ae6f-950c-43e5-b178-6b35b9e128a3.png)

Issue:
The dialog values are not translated with/by OWL.

@holdenrehg

**Comment by holdenrehg** [comment]
@Yenthe666 ready for another test here.

**Comment by holdenrehg** [comment]
And again @Yenthe666 , closed open PR, started new with the latest recommendation we got from Odoo. Take a look.

**Comment by Yenthe666** [comment]
Yep, this one looks a-okay! 👍 🥳
