### ISSUE TITLE
Invalid timeslot generation

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/rental#6]
Take a look at the following configuration of a rental product:
![image](https://user-images.githubusercontent.com/6352350/129587033-2c9f8b4b-7145-4261-85f2-c0aec7838611.png)

In the sample here it has a start time of 08:00 and an end time of 18:00 then you should get these starting slots:
08:00
09:00
10:00
11:00
12:00
13:00
14:00

End time slots should be:
12:00
13:00
14:00
15:00
16:00
17:00
18:00

However, it generates this:
![image](https://user-images.githubusercontent.com/6352350/129590274-c3868b0d-58e8-4186-9272-fc3115d9e3a1.png)

- If you'd book from 8AM to 12PM it would take the 4h rule for pricing. 
- If you would book from 8AM to 13PM it would take the 4h rule price plus one extra hour (so 250 + 50 which would mean 300).
- If you'd book from 8AM to 15PM it would take the 4h rule price plus three extra hours (so 250 for 4h + 3x50/extra hour, which would mean 400).
-  If you'd book from 8AM to 18PM it _should_ take the 8 hours rule with a cost of 350 (but that seems to be an Odoo bug/logic flaw issue, right?).

**Comment by Yenthe666** [comment]
@holdenrehg can you take a look and give me feedback? :)

**Comment by holdenrehg** [comment]
@Yenthe666 got some work done on this, but think I'm missing a scenario while testing.

So to confirm the functionality here:

- **Timeslots should always have an interval of 1 hour**. The current behavior is it takes the lowest rule and sets that as the interval.  Which is why you see the 8, 12, 16 intervals in your example above.
- **Since Extra Hour and Extra Day aren't required, what would happen in the scenario if Extra Hour is unset**, and a customer books 5 hours? So they would have 1 extra hour to charge, without any price.
- **The requested time should take the pricing of the greatest pricing rule that fits**. Like you said, yes we were having that bug with core Odoo. This module doesn't actually touch how prices are set, that's all handled by `sale_renting`. I'm sure it's possible to change, but that's a larger task in itself.

Let me know how you'd like to handle the second item above and then I'll have this ready to go.

**Comment by Yenthe666** [comment]
@holdenrehg 
> Timeslots should always have an interval of 1 hour. The current behavior is it takes the lowest rule and sets that as the interval. Which is why you see the 8, 12, 16 intervals in your example above.

It should follow the duration set on the pricing rule of the rental (field `duration` on the rental rule.
E.g you could have two variants where one variant has a `duration` of 4 and one variant has a `duration` of 8. If the product variant for "4" is generated (start time 08:00, end time 18:00) it would generate start slots like:
- 08:00
- 12:00
- 16:00
and end slots like:
- 12:00
- 16:00

>Since Extra Hour and Extra Day aren't required, what would happen in the scenario if Extra Hour is unset, and a customer books 5 hours? So they would have 1 extra hour to charge, without any price.

Let's make the field required so you need to fill in an extra cost. If any of the rules contains a unit of "Hours" the field `extra_hourly` will be required and has to be bigger than 0. If any of the rules contains a unit of "Days" the field `extra_daily` will be required and has to be bigger than 0. This way we will always have an extra price to apply.

>> The requested time should take the pricing of the greatest pricing rule that fits. Like you said, yes we were having that bug with core Odoo. This module doesn't actually touch how prices are set, that's all handled by sale_renting. I'm sure it's possible to change, but that's a larger task in itself.

Yeah, out of scope for our V1.0 at least.

**Comment by holdenrehg** [comment]
Hm, so then in your sample it shouldn't generate using an hourly interval like you're describing, right? Since your sample shows the smallest duration of `4h`. That's the current  functionality.

> In the sample here it has a start time of 08:00 and an end time of 18:00 then you should get these starting slots:
> 08:00
> 09:00
> 10:00
> 11:00
> 12:00
> 13:00
> 14:00
> 
> End time slots should be:
> 12:00
> 13:00
> 14:00
> 15:00
> 16:00
> 17:00
> 18:00

**Comment by TSOstefankeller** [comment]
Hi Rehg

In agreement with Yenthe, I will answer you directly.
The available slots should be as explained from Yenthe from the smallest duration.
The extra hours / days shouldnt have an impact on the calendar views start slot. Only for the ending ones.

So in our example:

Start slot
- 08:00
- 12:00
- 16:00
and end slots like:
- 12:00
- 13:00
- 14:00
- 15:00
- 16:00
- 17:00
- 18:00

**Comment by holdenrehg** [comment]
Got it @TSOstefankeller , thanks for the clarification!

**Comment by Yenthe666** [comment]
All of those cases should now be handled in our last updates :)
